/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ReportStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const ApprovalComment = IDL.Record({
  'status' : ReportStatus,
  'officerName' : IDL.Text,
  'officerPrincipal' : IDL.Principal,
  'comment' : IDL.Text,
  'timestamp' : Time,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const VehicleInspectionPublic = IDL.Record({
  'id' : IDL.Text,
  'vin' : IDL.Text,
  'damages' : IDL.Text,
  'model' : IDL.Text,
  'mileage' : IDL.Nat,
  'licensePlate' : IDL.Text,
  'approvalComments' : IDL.Vec(ApprovalComment),
  'inspectorPrincipal' : IDL.Principal,
  'reportStatus' : ReportStatus,
  'make' : IDL.Text,
  'inspectorName' : IDL.Text,
  'year' : IDL.Nat16,
  'notes' : IDL.Text,
  'timestamp' : Time,
  'photos' : IDL.Vec(ExternalBlob),
  'condition' : IDL.Text,
});
export const Role = IDL.Variant({
  'insuranceOfficer' : IDL.Null,
  'inspector' : IDL.Null,
});
export const UserProfilePublic = IDL.Record({
  'name' : IDL.Text,
  'role' : Role,
});
export const LetterheadInfoPublic = IDL.Record({
  'contactInfo' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
});
export const ReviewResult = IDL.Record({
  'status' : ReportStatus,
  'approvalHistory' : IDL.Vec(ApprovalComment),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : Role });
export const VehicleInspectionInput = IDL.Record({
  'id' : IDL.Text,
  'vin' : IDL.Text,
  'damages' : IDL.Text,
  'model' : IDL.Text,
  'mileage' : IDL.Nat,
  'licensePlate' : IDL.Text,
  'make' : IDL.Text,
  'year' : IDL.Nat16,
  'notes' : IDL.Text,
  'photos' : IDL.Vec(ExternalBlob),
  'condition' : IDL.Text,
});
export const LetterheadInfo = IDL.Record({
  'contactInfo' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllInspections' : IDL.Func(
      [],
      [IDL.Vec(VehicleInspectionPublic)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [UserProfilePublic], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInspection' : IDL.Func([IDL.Text], [VehicleInspectionPublic], ['query']),
  'getInspectionsByInspector' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(VehicleInspectionPublic)],
      ['query'],
    ),
  'getInspectionsByStatus' : IDL.Func(
      [ReportStatus],
      [IDL.Vec(VehicleInspectionPublic)],
      ['query'],
    ),
  'getLetterheadInfo' : IDL.Func([], [LetterheadInfoPublic], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfilePublic], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reviewInspection' : IDL.Func(
      [IDL.Text, ReportStatus, IDL.Text],
      [ReviewResult],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitInspection' : IDL.Func([VehicleInspectionInput], [], []),
  'updateLetterheadInfo' : IDL.Func([LetterheadInfo], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ReportStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const ApprovalComment = IDL.Record({
    'status' : ReportStatus,
    'officerName' : IDL.Text,
    'officerPrincipal' : IDL.Principal,
    'comment' : IDL.Text,
    'timestamp' : Time,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const VehicleInspectionPublic = IDL.Record({
    'id' : IDL.Text,
    'vin' : IDL.Text,
    'damages' : IDL.Text,
    'model' : IDL.Text,
    'mileage' : IDL.Nat,
    'licensePlate' : IDL.Text,
    'approvalComments' : IDL.Vec(ApprovalComment),
    'inspectorPrincipal' : IDL.Principal,
    'reportStatus' : ReportStatus,
    'make' : IDL.Text,
    'inspectorName' : IDL.Text,
    'year' : IDL.Nat16,
    'notes' : IDL.Text,
    'timestamp' : Time,
    'photos' : IDL.Vec(ExternalBlob),
    'condition' : IDL.Text,
  });
  const Role = IDL.Variant({
    'insuranceOfficer' : IDL.Null,
    'inspector' : IDL.Null,
  });
  const UserProfilePublic = IDL.Record({ 'name' : IDL.Text, 'role' : Role });
  const LetterheadInfoPublic = IDL.Record({
    'contactInfo' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
  });
  const ReviewResult = IDL.Record({
    'status' : ReportStatus,
    'approvalHistory' : IDL.Vec(ApprovalComment),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : Role });
  const VehicleInspectionInput = IDL.Record({
    'id' : IDL.Text,
    'vin' : IDL.Text,
    'damages' : IDL.Text,
    'model' : IDL.Text,
    'mileage' : IDL.Nat,
    'licensePlate' : IDL.Text,
    'make' : IDL.Text,
    'year' : IDL.Nat16,
    'notes' : IDL.Text,
    'photos' : IDL.Vec(ExternalBlob),
    'condition' : IDL.Text,
  });
  const LetterheadInfo = IDL.Record({
    'contactInfo' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllInspections' : IDL.Func(
        [],
        [IDL.Vec(VehicleInspectionPublic)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [UserProfilePublic], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInspection' : IDL.Func(
        [IDL.Text],
        [VehicleInspectionPublic],
        ['query'],
      ),
    'getInspectionsByInspector' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(VehicleInspectionPublic)],
        ['query'],
      ),
    'getInspectionsByStatus' : IDL.Func(
        [ReportStatus],
        [IDL.Vec(VehicleInspectionPublic)],
        ['query'],
      ),
    'getLetterheadInfo' : IDL.Func([], [LetterheadInfoPublic], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [UserProfilePublic],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reviewInspection' : IDL.Func(
        [IDL.Text, ReportStatus, IDL.Text],
        [ReviewResult],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitInspection' : IDL.Func([VehicleInspectionInput], [], []),
    'updateLetterheadInfo' : IDL.Func([LetterheadInfo], [], []),
  });
};

export const init = ({ IDL }) => { return []; };