/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApprovalComment {
  'status' : ReportStatus,
  'officerName' : string,
  'officerPrincipal' : Principal,
  'comment' : string,
  'timestamp' : Time,
}
export interface ApprovalCommentPublic {
  'status' : ReportStatus,
  'officerName' : string,
  'officerPrincipal' : Principal,
  'comment' : string,
  'timestamp' : Time,
}
export type ExternalBlob = Uint8Array;
export type GlassOption = { 'ozoneProtective' : null } |
  { 'tinted' : null } |
  { 'other' : string } |
  { 'clear' : null } |
  { 'privacyGlass' : null } |
  { 'sunroofTinted' : null } |
  { 'heatResistant' : null } |
  { 'factoryTinted' : null } |
  { 'impactResistant' : null } |
  { 'aftermarketTinted' : null } |
  { 'acoustic' : null } |
  { 'solarControl' : null } |
  { 'laminated' : null };
export interface LetterheadInfo {
  'contactInfo' : string,
  'address' : string,
  'companyName' : string,
}
export interface LetterheadInfoPublic {
  'contactInfo' : string,
  'address' : string,
  'companyName' : string,
}
export type ReportStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ReviewResult {
  'status' : ReportStatus,
  'approvalHistory' : Array<ApprovalComment>,
}
export type Role = { 'insuranceOfficer' : null } |
  { 'inspector' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : Role }
export interface UserProfilePublic { 'name' : string, 'role' : Role }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VehicleInspectionInput {
  'id' : string,
  'vin' : string,
  'damages' : string,
  'model' : string,
  'mileage' : bigint,
  'licensePlate' : string,
  'make' : string,
  'year' : number,
  'notes' : string,
  'glassOption' : GlassOption,
  'photos' : Array<ExternalBlob>,
  'condition' : string,
}
export interface VehicleInspectionPublic {
  'id' : string,
  'vin' : string,
  'damages' : string,
  'model' : string,
  'mileage' : bigint,
  'licensePlate' : string,
  'approvalComments' : Array<ApprovalCommentPublic>,
  'inspectorPrincipal' : Principal,
  'reportStatus' : ReportStatus,
  'make' : string,
  'inspectorName' : string,
  'year' : number,
  'notes' : string,
  'timestamp' : Time,
  'glassOption' : GlassOption,
  'photos' : Array<ExternalBlob>,
  'condition' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllInspections' : ActorMethod<[], Array<VehicleInspectionPublic>>,
  'getCallerUserProfile' : ActorMethod<[], UserProfilePublic>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInspection' : ActorMethod<[string], VehicleInspectionPublic>,
  'getInspectionsByInspector' : ActorMethod<
    [Principal],
    Array<VehicleInspectionPublic>
  >,
  'getInspectionsByStatus' : ActorMethod<
    [ReportStatus],
    Array<VehicleInspectionPublic>
  >,
  'getLetterheadInfo' : ActorMethod<[], LetterheadInfoPublic>,
  'getUserProfile' : ActorMethod<[Principal], UserProfilePublic>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reviewInspection' : ActorMethod<
    [string, ReportStatus, string],
    ReviewResult
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitInspection' : ActorMethod<[VehicleInspectionInput], undefined>,
  'updateLetterheadInfo' : ActorMethod<[LetterheadInfo], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];