/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ApprovalCommentPublic {
    status: ReportStatus;
    officerName: string;
    officerPrincipal: Principal;
    comment: string;
    timestamp: Time;
}
export interface ApprovalComment {
    status: ReportStatus;
    officerName: string;
    officerPrincipal: Principal;
    comment: string;
    timestamp: Time;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface LetterheadInfo {
    contactInfo: string;
    address: string;
    companyName: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface VehicleInspectionInput {
    id: string;
    vin: string;
    damages: string;
    model: string;
    mileage: bigint;
    licensePlate: string;
    make: string;
    year: number;
    notes: string;
    glassOption: GlassOption;
    photos: Array<ExternalBlob>;
    condition: string;
}
export type GlassOption = {
    __kind__: "ozoneProtective";
    ozoneProtective: null;
} | {
    __kind__: "tinted";
    tinted: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "clear";
    clear: null;
} | {
    __kind__: "privacyGlass";
    privacyGlass: null;
} | {
    __kind__: "sunroofTinted";
    sunroofTinted: null;
} | {
    __kind__: "heatResistant";
    heatResistant: null;
} | {
    __kind__: "factoryTinted";
    factoryTinted: null;
} | {
    __kind__: "impactResistant";
    impactResistant: null;
} | {
    __kind__: "aftermarketTinted";
    aftermarketTinted: null;
} | {
    __kind__: "acoustic";
    acoustic: null;
} | {
    __kind__: "solarControl";
    solarControl: null;
} | {
    __kind__: "laminated";
    laminated: null;
};
export interface UserProfilePublic {
    name: string;
    role: Role;
}
export interface ReviewResult {
    status: ReportStatus;
    approvalHistory: Array<ApprovalComment>;
}
export interface VehicleInspectionPublic {
    id: string;
    vin: string;
    damages: string;
    model: string;
    mileage: bigint;
    licensePlate: string;
    approvalComments: Array<ApprovalCommentPublic>;
    inspectorPrincipal: Principal;
    reportStatus: ReportStatus;
    make: string;
    inspectorName: string;
    year: number;
    notes: string;
    timestamp: Time;
    glassOption: GlassOption;
    photos: Array<ExternalBlob>;
    condition: string;
}
export interface LetterheadInfoPublic {
    contactInfo: string;
    address: string;
    companyName: string;
}
export interface UserProfile {
    name: string;
    role: Role;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ReportStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum Role {
    insuranceOfficer = "insuranceOfficer",
    inspector = "inspector"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllInspections(): Promise<Array<VehicleInspectionPublic>>;
    getCallerUserProfile(): Promise<UserProfilePublic>;
    getCallerUserRole(): Promise<UserRole>;
    getInspection(reportId: string): Promise<VehicleInspectionPublic>;
    getInspectionsByInspector(inspectorPrincipal: Principal): Promise<Array<VehicleInspectionPublic>>;
    getInspectionsByStatus(status: ReportStatus): Promise<Array<VehicleInspectionPublic>>;
    getLetterheadInfo(): Promise<LetterheadInfoPublic>;
    getUserProfile(user: Principal): Promise<UserProfilePublic>;
    isCallerAdmin(): Promise<boolean>;
    reviewInspection(reportId: string, status: ReportStatus, comment: string): Promise<ReviewResult>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitInspection(input: VehicleInspectionInput): Promise<void>;
    updateLetterheadInfo(newInfo: LetterheadInfo): Promise<void>;
}
import type { ApprovalComment as _ApprovalComment, ApprovalCommentPublic as _ApprovalCommentPublic, ExternalBlob as _ExternalBlob, GlassOption as _GlassOption, ReportStatus as _ReportStatus, ReviewResult as _ReviewResult, Role as _Role, Time as _Time, UserProfile as _UserProfile, UserProfilePublic as _UserProfilePublic, UserRole as _UserRole, VehicleInspectionInput as _VehicleInspectionInput, VehicleInspectionPublic as _VehicleInspectionPublic, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllInspections(): Promise<Array<VehicleInspectionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInspections();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInspections();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_UserProfilePublic_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_UserProfilePublic_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInspection(arg0: string): Promise<VehicleInspectionPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getInspection(arg0);
                return from_candid_VehicleInspectionPublic_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInspection(arg0);
            return from_candid_VehicleInspectionPublic_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInspectionsByInspector(arg0: Principal): Promise<Array<VehicleInspectionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInspectionsByInspector(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInspectionsByInspector(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInspectionsByStatus(arg0: ReportStatus): Promise<Array<VehicleInspectionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInspectionsByStatus(to_candid_ReportStatus_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInspectionsByStatus(to_candid_ReportStatus_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLetterheadInfo(): Promise<LetterheadInfoPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getLetterheadInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLetterheadInfo();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_UserProfilePublic_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_UserProfilePublic_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async reviewInspection(arg0: string, arg1: ReportStatus, arg2: string): Promise<ReviewResult> {
        if (this.processError) {
            try {
                const result = await this.actor.reviewInspection(arg0, to_candid_ReportStatus_n28(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_ReviewResult_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reviewInspection(arg0, to_candid_ReportStatus_n28(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_ReviewResult_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitInspection(arg0: VehicleInspectionInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInspection(await to_candid_VehicleInspectionInput_n38(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInspection(await to_candid_VehicleInspectionInput_n38(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateLetterheadInfo(arg0: LetterheadInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLetterheadInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLetterheadInfo(arg0);
            return result;
        }
    }
}
function from_candid_ApprovalCommentPublic_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalCommentPublic): ApprovalCommentPublic {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalComment_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalComment): ApprovalComment {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_GlassOption_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GlassOption): GlassOption {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ReportStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportStatus): ReportStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ReviewResult_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReviewResult): ReviewResult {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_VehicleInspectionPublic_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleInspectionPublic): Promise<VehicleInspectionPublic> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    vin: string;
    damages: string;
    model: string;
    mileage: bigint;
    licensePlate: string;
    approvalComments: Array<_ApprovalCommentPublic>;
    inspectorPrincipal: Principal;
    reportStatus: _ReportStatus;
    make: string;
    inspectorName: string;
    year: number;
    notes: string;
    timestamp: _Time;
    glassOption: _GlassOption;
    photos: Array<_ExternalBlob>;
    condition: string;
}): Promise<{
    id: string;
    vin: string;
    damages: string;
    model: string;
    mileage: bigint;
    licensePlate: string;
    approvalComments: Array<ApprovalCommentPublic>;
    inspectorPrincipal: Principal;
    reportStatus: ReportStatus;
    make: string;
    inspectorName: string;
    year: number;
    notes: string;
    timestamp: Time;
    glassOption: GlassOption;
    photos: Array<ExternalBlob>;
    condition: string;
}> {
    return {
        id: value.id,
        vin: value.vin,
        damages: value.damages,
        model: value.model,
        mileage: value.mileage,
        licensePlate: value.licensePlate,
        approvalComments: from_candid_vec_n13(_uploadFile, _downloadFile, value.approvalComments),
        inspectorPrincipal: value.inspectorPrincipal,
        reportStatus: from_candid_ReportStatus_n16(_uploadFile, _downloadFile, value.reportStatus),
        make: value.make,
        inspectorName: value.inspectorName,
        year: value.year,
        notes: value.notes,
        timestamp: value.timestamp,
        glassOption: from_candid_GlassOption_n18(_uploadFile, _downloadFile, value.glassOption),
        photos: await from_candid_vec_n20(_uploadFile, _downloadFile, value.photos),
        condition: value.condition
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ReportStatus;
    officerName: string;
    officerPrincipal: Principal;
    comment: string;
    timestamp: _Time;
}): {
    status: ReportStatus;
    officerName: string;
    officerPrincipal: Principal;
    comment: string;
    timestamp: Time;
} {
    return {
        status: from_candid_ReportStatus_n16(_uploadFile, _downloadFile, value.status),
        officerName: value.officerName,
        officerPrincipal: value.officerPrincipal,
        comment: value.comment,
        timestamp: value.timestamp
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _Role;
}): {
    name: string;
    role: Role;
} {
    return {
        name: value.name,
        role: from_candid_Role_n24(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ReportStatus;
    approvalHistory: Array<_ApprovalComment>;
}): {
    status: ReportStatus;
    approvalHistory: Array<ApprovalComment>;
} {
    return {
        status: from_candid_ReportStatus_n16(_uploadFile, _downloadFile, value.status),
        approvalHistory: from_candid_vec_n32(_uploadFile, _downloadFile, value.approvalHistory)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ReportStatus {
    return "pending" in value ? ReportStatus.pending : "approved" in value ? ReportStatus.approved : "rejected" in value ? ReportStatus.rejected : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ozoneProtective: null;
} | {
    tinted: null;
} | {
    other: string;
} | {
    clear: null;
} | {
    privacyGlass: null;
} | {
    sunroofTinted: null;
} | {
    heatResistant: null;
} | {
    factoryTinted: null;
} | {
    impactResistant: null;
} | {
    aftermarketTinted: null;
} | {
    acoustic: null;
} | {
    solarControl: null;
} | {
    laminated: null;
}): {
    __kind__: "ozoneProtective";
    ozoneProtective: null;
} | {
    __kind__: "tinted";
    tinted: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "clear";
    clear: null;
} | {
    __kind__: "privacyGlass";
    privacyGlass: null;
} | {
    __kind__: "sunroofTinted";
    sunroofTinted: null;
} | {
    __kind__: "heatResistant";
    heatResistant: null;
} | {
    __kind__: "factoryTinted";
    factoryTinted: null;
} | {
    __kind__: "impactResistant";
    impactResistant: null;
} | {
    __kind__: "aftermarketTinted";
    aftermarketTinted: null;
} | {
    __kind__: "acoustic";
    acoustic: null;
} | {
    __kind__: "solarControl";
    solarControl: null;
} | {
    __kind__: "laminated";
    laminated: null;
} {
    return "ozoneProtective" in value ? {
        __kind__: "ozoneProtective",
        ozoneProtective: value.ozoneProtective
    } : "tinted" in value ? {
        __kind__: "tinted",
        tinted: value.tinted
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "clear" in value ? {
        __kind__: "clear",
        clear: value.clear
    } : "privacyGlass" in value ? {
        __kind__: "privacyGlass",
        privacyGlass: value.privacyGlass
    } : "sunroofTinted" in value ? {
        __kind__: "sunroofTinted",
        sunroofTinted: value.sunroofTinted
    } : "heatResistant" in value ? {
        __kind__: "heatResistant",
        heatResistant: value.heatResistant
    } : "factoryTinted" in value ? {
        __kind__: "factoryTinted",
        factoryTinted: value.factoryTinted
    } : "impactResistant" in value ? {
        __kind__: "impactResistant",
        impactResistant: value.impactResistant
    } : "aftermarketTinted" in value ? {
        __kind__: "aftermarketTinted",
        aftermarketTinted: value.aftermarketTinted
    } : "acoustic" in value ? {
        __kind__: "acoustic",
        acoustic: value.acoustic
    } : "solarControl" in value ? {
        __kind__: "solarControl",
        solarControl: value.solarControl
    } : "laminated" in value ? {
        __kind__: "laminated",
        laminated: value.laminated
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    insuranceOfficer: null;
} | {
    inspector: null;
}): Role {
    return "insuranceOfficer" in value ? Role.insuranceOfficer : "inspector" in value ? Role.inspector : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VehicleInspectionPublic>): Promise<Array<VehicleInspectionPublic>> {
    return await Promise.all(value.map(async (x)=>await from_candid_VehicleInspectionPublic_n11(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApprovalCommentPublic>): Array<ApprovalCommentPublic> {
    return value.map((x)=>from_candid_ApprovalCommentPublic_n14(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApprovalComment>): Array<ApprovalComment> {
    return value.map((x)=>from_candid_ApprovalComment_n33(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_GlassOption_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GlassOption): _GlassOption {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_ReportStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): _ReportStatus {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_VehicleInspectionInput_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleInspectionInput): Promise<_VehicleInspectionInput> {
    return await to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: Role;
}): {
    name: string;
    role: _Role;
} {
    return {
        name: value.name,
        role: to_candid_Role_n36(_uploadFile, _downloadFile, value.role)
    };
}
async function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    vin: string;
    damages: string;
    model: string;
    mileage: bigint;
    licensePlate: string;
    make: string;
    year: number;
    notes: string;
    glassOption: GlassOption;
    photos: Array<ExternalBlob>;
    condition: string;
}): Promise<{
    id: string;
    vin: string;
    damages: string;
    model: string;
    mileage: bigint;
    licensePlate: string;
    make: string;
    year: number;
    notes: string;
    glassOption: _GlassOption;
    photos: Array<_ExternalBlob>;
    condition: string;
}> {
    return {
        id: value.id,
        vin: value.vin,
        damages: value.damages,
        model: value.model,
        mileage: value.mileage,
        licensePlate: value.licensePlate,
        make: value.make,
        year: value.year,
        notes: value.notes,
        glassOption: to_candid_GlassOption_n40(_uploadFile, _downloadFile, value.glassOption),
        photos: await to_candid_vec_n42(_uploadFile, _downloadFile, value.photos),
        condition: value.condition
    };
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ReportStatus.pending ? {
        pending: null
    } : value == ReportStatus.approved ? {
        approved: null
    } : value == ReportStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    insuranceOfficer: null;
} | {
    inspector: null;
} {
    return value == Role.insuranceOfficer ? {
        insuranceOfficer: null
    } : value == Role.inspector ? {
        inspector: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "ozoneProtective";
    ozoneProtective: null;
} | {
    __kind__: "tinted";
    tinted: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "clear";
    clear: null;
} | {
    __kind__: "privacyGlass";
    privacyGlass: null;
} | {
    __kind__: "sunroofTinted";
    sunroofTinted: null;
} | {
    __kind__: "heatResistant";
    heatResistant: null;
} | {
    __kind__: "factoryTinted";
    factoryTinted: null;
} | {
    __kind__: "impactResistant";
    impactResistant: null;
} | {
    __kind__: "aftermarketTinted";
    aftermarketTinted: null;
} | {
    __kind__: "acoustic";
    acoustic: null;
} | {
    __kind__: "solarControl";
    solarControl: null;
} | {
    __kind__: "laminated";
    laminated: null;
}): {
    ozoneProtective: null;
} | {
    tinted: null;
} | {
    other: string;
} | {
    clear: null;
} | {
    privacyGlass: null;
} | {
    sunroofTinted: null;
} | {
    heatResistant: null;
} | {
    factoryTinted: null;
} | {
    impactResistant: null;
} | {
    aftermarketTinted: null;
} | {
    acoustic: null;
} | {
    solarControl: null;
} | {
    laminated: null;
} {
    return value.__kind__ === "ozoneProtective" ? {
        ozoneProtective: value.ozoneProtective
    } : value.__kind__ === "tinted" ? {
        tinted: value.tinted
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "clear" ? {
        clear: value.clear
    } : value.__kind__ === "privacyGlass" ? {
        privacyGlass: value.privacyGlass
    } : value.__kind__ === "sunroofTinted" ? {
        sunroofTinted: value.sunroofTinted
    } : value.__kind__ === "heatResistant" ? {
        heatResistant: value.heatResistant
    } : value.__kind__ === "factoryTinted" ? {
        factoryTinted: value.factoryTinted
    } : value.__kind__ === "impactResistant" ? {
        impactResistant: value.impactResistant
    } : value.__kind__ === "aftermarketTinted" ? {
        aftermarketTinted: value.aftermarketTinted
    } : value.__kind__ === "acoustic" ? {
        acoustic: value.acoustic
    } : value.__kind__ === "solarControl" ? {
        solarControl: value.solarControl
    } : value.__kind__ === "laminated" ? {
        laminated: value.laminated
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n43(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
